version: "3"

services:
  people-counter:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
